blueprint:
  name: Set Controllable Entity States
  description: >
    Turns multiple entities on or off and logs the operation.
  domain: script
  input:
    target_entities:
      name: Target Entities
      selector:
        entity:
          multiple: true
          domain:
            - switch
            - light
            - input_boolean
            - fan
            - automation

fields:
  desired_state:
    name: Desired State
    default: true
    selector:
      boolean: {}

variables:
  desired: "{{ 'on' if desired_state else 'off' }}"
  action_service: "{{ 'homeassistant.turn_on' if desired_state else 'homeassistant.turn_off' }}"

sequence:
  - service: system_log.write
    data:
      level: info
      message: >
        "Requested state={{ desired }} for entities: {{ target_entities | join(', ') }}"

  - service: "{{ action_service }}"
    target:
      entity_id: !input target_entities

  - service: system_log.write
    data:
      level: info
      message: >
        "Service {{ action_service }} executed for {{ target_entities | length }} entities"

mode: queued
max: 10
